// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfOzSSR1585DlKleJDEbW6gqCCN4mTX-I',
    appId: '1:282579178585:web:4185dbdd4a6e1810bf8d48',
    messagingSenderId: '282579178585',
    projectId: 'registration-624ed',
    authDomain: 'registration-624ed.firebaseapp.com',
    storageBucket: 'registration-624ed.firebasestorage.app',
    measurementId: 'G-CTECZYKHQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn1yZwcgKORiDvsbXIg6UAzNPuH93ERqw',
    appId: '1:282579178585:android:9db94bcb4480df4ebf8d48',
    messagingSenderId: '282579178585',
    projectId: 'registration-624ed',
    storageBucket: 'registration-624ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoCDy06uR5E5D4galzx9-4mwqr-fV3ZnU',
    appId: '1:282579178585:ios:40a325a5cc56d735bf8d48',
    messagingSenderId: '282579178585',
    projectId: 'registration-624ed',
    storageBucket: 'registration-624ed.firebasestorage.app',
    iosBundleId: 'com.example.flRembulat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoCDy06uR5E5D4galzx9-4mwqr-fV3ZnU',
    appId: '1:282579178585:ios:40a325a5cc56d735bf8d48',
    messagingSenderId: '282579178585',
    projectId: 'registration-624ed',
    storageBucket: 'registration-624ed.firebasestorage.app',
    iosBundleId: 'com.example.flRembulat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfOzSSR1585DlKleJDEbW6gqCCN4mTX-I',
    appId: '1:282579178585:web:a753e8ec0b5f9c92bf8d48',
    messagingSenderId: '282579178585',
    projectId: 'registration-624ed',
    authDomain: 'registration-624ed.firebaseapp.com',
    storageBucket: 'registration-624ed.firebasestorage.app',
    measurementId: 'G-ZGST44EVF9',
  );
}
